
name : experiment

on :
  push :
    branches : [ experiment ]

jobs :

  Full :
    if : "startsWith( github.event.head_commit.message, 'experiment' )"
    runs-on : ${{ matrix.os }}
    strategy :
      fail-fast : false
      matrix :
        os : [ ubuntu-latest, windows-latest, macos-latest ]
        node-version : [ 10.x, 12.x, 13.x, 14.x, 15.x ]
    steps :
    - run : git config --global core.autocrlf input
    - run : git config --global user.email "testing@testing.com"
    - run : git config --global user.name "Testing"
    - uses : actions/checkout@v2
    - name : ${{ matrix.node-version }}
      uses : actions/setup-node@v1
      with :
        node-version : ${{ matrix.node-version }}
    - run : npm i
    - name : npm test
      run : node proto/wtools/abase/l4_process.test/Execution.test.s r:experimentIpcDeasync v:10
      env :
        WTOOLS_BOT_TOKEN : ${{ secrets.WTOOLS_BOT_TOKEN }}
