
name : publish

on :
  push :
    branches : [ windows ]

jobs :

  Full :
    if : "startsWith( github.event.head_commit.message, 'version' )"
    runs-on : ${{ matrix.os }}
    strategy :
      fail-fast : false
      matrix :
        os : [ windows-latest ]
        ## node-version : [ 10.x, 12.x, 13.x, 14.x, 15.x ]
        node-version : [ 10.x, 12.9.1, 13.x, 14.x, 15.x, 10.x, 12.9.1, 13.x, 14.x, 15.x, 10.x, 12.9.1, 13.x, 14.x, 15.x ]
    steps :
    - run : git config --global core.autocrlf input
    - run : git config --global user.email "testing@testing.com"
    - run : git config --global user.name "Testing"
    - uses : actions/checkout@v2
      with :
        fetch-depth: 2
    - name : ${{ matrix.node-version }}
      uses : actions/setup-node@v1
      with :
        node-version : ${{ matrix.node-version }}
    - run : npm i
    - name : run test
      run : node proto/wtools/abase/l4_process.test/Execution.test.s r:childrenWindows v:10
      env :
        WTOOLS_BOT_TOKEN : ${{ secrets.WTOOLS_BOT_TOKEN }}
